### ISSUE TITLE
Blockchain download fails on new 2.2.0 install

### ISSUE THREAD

**Issue by bitmelt** [PoC-Consortium/burstcoin#322] opened 2018-05-29 18:36 UTC
I made a fresh install of the 2.2.0 release (dropped the database and db user and recreated them.)  Running `./burst.sh` works and it initializes the database and starts downloading the blocks.  Some time after block 15000 it throws the exceptions below.

**My environment:**

Mac OS High Sierra 10.13.4
MySQL server 10.2.13-MariaDB
Java 1.8.0_162

**Exceptions:**

```
[INFO] 2018-05-29 14:18:49 brs.BlockchainProcessorImpl - processed block 15000
[INFO] 2018-05-29 14:19:14 brs.statistics.StatisticsManagerImpl - handling 20.83 blocks/s account cache hit ratio now/total:99.91%/99.62%
[INFO] 2018-05-29 14:19:36 brs.statistics.StatisticsManagerImpl - handling 22.73 blocks/s account cache hit ratio now/total:99.86%/99.63%
[SEVERE] 2018-05-29 14:19:49 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
brs.Account$DoubleSpendingException: Unconfirmed (3606562031645) exceeds confirmed (3506562031645) balance or quantity for account 9520002821326478261
	at brs.Account.checkBalance(Account.java:308)
	at brs.Account.checkBalance(Account.java:313)
	at brs.services.impl.AccountServiceImpl.addToBalanceNQT(AccountServiceImpl.java:220)
	at brs.assetexchange.OrderServiceImpl.matchOrders(OrderServiceImpl.java:141)
	at brs.assetexchange.OrderServiceImpl.addAskOrder(OrderServiceImpl.java:100)
	at brs.assetexchange.AssetExchangeImpl.addAskOrder(AssetExchangeImpl.java:88)
	at brs.TransactionType$ColoredCoins$3.applyAttachment(TransactionType.java:1019)
	at brs.TransactionType.apply(TransactionType.java:283)
	at brs.Attachment$AbstractAttachment.apply(Attachment.java:115)
	at brs.services.impl.TransactionServiceImpl.apply(TransactionServiceImpl.java:75)
	at brs.services.impl.BlockServiceImpl.apply(BlockServiceImpl.java:162)
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1038)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:981)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:279)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[SEVERE] 2018-05-29 14:19:59 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn=81) Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
	at org.jooq_3.10.5.MARIADB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2239)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:127)
	at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:154)
	at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:168)
	at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:806)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:980)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:279)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=81) Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:171)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:452)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 14 more
Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
Query is: insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [9116249626711803666,3,3981928,8014735931978063767,693427067949,3100000000,1760,<bytearray:��ۖ�H��`5_Ȫ
            ��L�7��\�����e>,<bytearray:����:o�e���t�H���C� ���M8�1>,<bytearray:�ۙ���>,4526869,16324,<bytearray:&w6,B�Up|EDwa|�D��y�1���>,<bytearray:'Q�Z;���Z~+-,��J��\�9P�u�
                                                    �-���kPf�6�et�j�ѕ}d��l.;Y>,<bytearray:S.��m�م<JG�u�(d�f^3��j�s��>,4667403007241856869,42994212,<null>]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 21 more
```

**Comment by xyphos10** [comment] 2018-05-29 19:01
I have also attempted to setup a new wallet with version 2.2.0 starting with a blank database but it gets stuck at block 16324 with a similar error.

My System
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Mariadb version 10.3.7
OS: Windows10 64Bit

Error Produced:

`[SEVERE] 2018-05-29 13:00:53 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn=40) Cannot add or update a child row: a foreign key constraint fails (`burst220`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
        at org.jooq_3.10.5.MARIADB.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2239)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
        at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:127)
        at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:154)
        at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:168)
        at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:806)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:980)
        at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:279)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=40) Cannot add or update a child row: a foreign key constraint fails (`burst220`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:171)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:452)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
        ... 14 more
Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`burst220`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
Query is: insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [9116249626711803666,3,3981928,8014735931978063767,693427067949,3100000000,1760,<bytearraDwa|┼D█┌y┴1│■î>,<bytearray:'Q┴Z;?╛âZ~+-,óΦJêα\√9P┼u ª»-±å╗╬ΦkPf?6Çetöjú╤ò}d▓⌠l.; Y>,<bytearray:S.╪∞mÜ┘à<JG╦u┼(d¡f^3╫ⁿjás?╟>,4667403007241856869,42994212,<null>]
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
        ... 21 more
`

**Comment by InjectedPie** [comment] 2018-05-29 22:55
same here @ block 16323
env:
Windows Server 2012R2
H2
Java build 10.0.0.1 +10

[SEVERE] 2018-05-30 00:49:41 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
brs.Account$DoubleSpendingException: Unconfirmed (3606562031645) exceeds confirmed (3506562031645) balance or quantity for account 9520002821326478261
	at brs.Account.checkBalance(Account.java:308)
	at brs.Account.checkBalance(Account.java:313)
	at brs.services.impl.AccountServiceImpl.addToBalanceNQT(AccountServiceImpl.java:220)
	at brs.assetexchange.OrderServiceImpl.matchOrders(OrderServiceImpl.java:141)
	at brs.assetexchange.OrderServiceImpl.addAskOrder(OrderServiceImpl.java:100)
	at brs.assetexchange.AssetExchangeImpl.addAskOrder(AssetExchangeImpl.java:88)
	at brs.TransactionType$ColoredCoins$3.applyAttachment(TransactionType.java:1019)
	at brs.TransactionType.apply(TransactionType.java:283)
	at brs.Attachment$AbstractAttachment.apply(Attachment.java:115)
	at brs.services.impl.TransactionServiceImpl.apply(TransactionServiceImpl.java:75)
	at brs.services.impl.BlockServiceImpl.apply(BlockServiceImpl.java:162)
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1038)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:981)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:279)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[SEVERE] 2018-05-30 00:49:51 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (cast(? as bigint), cast(? as int), cast(? as int), cast(? as bigint), cast(? as bigint), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as bigint), cast(? as binary))]; Referentielle Integrität verletzt: "CONSTRAINT_59: PUBLIC.""block"" FOREIGN KEY(""previous_block_id"") REFERENCES PUBLIC.""block""(""id"") (8014735931978063767)"
Referential integrity constraint violation: "CONSTRAINT_59: PUBLIC.""block"" FOREIGN KEY(""previous_block_id"") REFERENCES PUBLIC.""block""(""id"") (8014735931978063767)"; SQL statement:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (cast(? as bigint), cast(? as int), cast(? as int), cast(? as bigint), cast(? as bigint), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as bigint), cast(? as binary)) [23506-196]
	at org.jooq_3.10.5.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2239)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:127)
	at brs.db.sql.SqlBlockDb.saveBlock(SqlBlockDb.java:154)
	at brs.db.sql.SqlBlockchainStore.addBlock(SqlBlockchainStore.java:168)
	at brs.BlockchainProcessorImpl.addBlock(BlockchainProcessorImpl.java:806)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:980)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:279)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Referentielle Integrität verletzt: "CONSTRAINT_59: PUBLIC.""block"" FOREIGN KEY(""previous_block_id"") REFERENCES PUBLIC.""block""(""id"") (8014735931978063767)"
Referential integrity constraint violation: "CONSTRAINT_59: PUBLIC.""block"" FOREIGN KEY(""previous_block_id"") REFERENCES PUBLIC.""block""(""id"") (8014735931978063767)"; SQL statement:
insert into "block" ("id", "version", "timestamp", "previous_block_id", "total_amount", "total_fee", "payload_length", "generator_public_key", "previous_block_hash", "cumulative_difficulty", "base_target", "height", "generation_signature", "block_signature", "payload_hash", "generator_id", "nonce", "ats") values (cast(? as bigint), cast(? as int), cast(? as int), cast(? as bigint), cast(? as bigint), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as int), cast(? as binary), cast(? as binary), cast(? as binary), cast(? as bigint), cast(? as bigint), cast(? as binary)) [23506-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:371)
	at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:313)
	at org.h2.table.Table.fireConstraints(Table.java:980)
	at org.h2.table.Table.fireAfterRow(Table.java:998)
	at org.h2.command.dml.Insert.insertRows(Insert.java:161)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:207)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:452)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 13 more

**Comment by ac0v** [comment] 2018-05-30 03:53
please download 2.2.0 once again and redo the sync. should be fixed (tag has been adjusted)

**Comment by bitmelt** [comment] 2018-05-30 18:21
The latest 2.2.0 release works.  From a fresh install and empty database, it downloaded all the blocks up to the current time without any errors.  Thanks!

**Comment by xyphos10** [comment] 2018-05-30 20:36
I can confirm as well that the new release is now syncing without problems

**Comment by ac0v** [comment] 2018-05-30 23:40
thx for reporting and re- verifying.

**Closed by ac0v** 2018-05-30 23:40 UTC
