### ISSUE TITLE
Fork handling issue

### ISSUE THREAD

**Issue by modislaszlo** [PoC-Consortium/burstcoin#348] opened 2018-06-18 17:57 UTC
Hello,

I updated the wallet from 2.2.0 and before that from 1.3.6. I'm running the wallet on a raspberry pi compiled from sources(using tag 2.2.1, commit 9f8968f92bddc08a563363ef57f4ae324e922e35).

I'm getting the following exception:

[SEVERE] 2018-06-18 20:38:40 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 17315627258521467547 transaction: {"senderPublicKey":"18f6f49edb73a5528ee0b12a0f907db1a3baf98f9a4b9bf9e62710a79cc04e2d","signature":"e657ebd9029d1bd31196c6540d9618eb614e25fb65f345d2eab2e121336bcc098a12c38b11605ff763f6c85d275942f30aeeee6904b507d05a6e7f2375921672","feeNQT":735000,"type":0,"version":1,"ecBlockId":"13325253500815200146","attachment":{},"subtype":0,"amountNQT":2850000000000,"recipient":"10267474793015653000","ecBlockHeight":501724,"deadline":1440,"timestamp":121361352}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1016)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:990)
	at brs.BlockchainProcessorImpl.lambda$new$64(BlockchainProcessorImpl.java:284)
	at brs.util.ThreadPool.lambda$start$12(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I already popped off 1000+ blocks and the wallet got stuck at same height(501733). Didn't had issues before(except the known issues in 1.3.6 and 2.2.0)

I'm importing the db hopefully that will fix the issue.

**Comment by COhsrt** [comment] 2018-06-18 21:42
1.36cg was incompatible around Block 500003 and 2.2.0 had a bug. So you would need to pop off more probably.
Anyway starting over with a freshly imported database will work.

**Comment by ac0v** [comment] 2018-06-20 18:22
that's a duplicate of #343 - your db is corrupt. please delete it - reimport or resync.

**Closed by ac0v** 2018-06-20 18:22 UTC
