### ISSUE TITLE
Performance problems in chrome / too many http requests / nrs.crowdfunding.js sucks

### ISSUE THREAD

**Issue by BraindeadOne** [PoC-Consortium/burstcoin#69] opened 2018-01-14 14:14 UTC
If the server hosting the wallet is too slow in responding to the wallet`s http requests chrome freezes for multiple seconds. (also see here: https://www.reddit.com/r/burstcoin/comments/7q143b/online_wallet_is_lagging/)

The main reason for this seem to be the thousands of unnecessary http requests started by the crowdfunding js code. From what i can see there are about 3000 unneeded requests on the login page!

The problematic code is already executed on the login page and continues to run when logged in - even if you never opened the crowdfunding page. 

There are hundreds of http-requests for "getATLong",  "getAT", "getBlockchainStatus" etc. 
- getATLong / hex2Long: those should be implemented in JS (if possible). There should at least be a cache and a lock to prevent multiple requests for the same value (currently many reqs for 0x0).
- getBlockchainStatus: This should only be called once every few seconds at most, not for every at
- getAT: this should be batched so that multiple ATs can be requested in a single http request

As a hotfix it should be enough to move the current $(document).ready()-code in nrs.crowdfunding.js to a function that is called when you click on the corresponding menu entry. 

Disabling the aforementioned method reduces the number of requests from 3k to <100

**Comment by EmilianSpo** [comment] 2018-01-14 14:22
Got the online wallet freezing too sometimes, good to see it fixed

**Comment by modislaszlo** [comment] 2018-01-20 10:28
Anyone has an ETA when this will be fixed? Online wallets are literally unusable.

**Comment by InjectedPie** [comment] 2018-01-24 18:29
its caused by a change between the 1.2.8 and the 1.3.6cg bugging it to load everything

**Comment by rico666** [comment] 2018-01-25 08:39
I think this has been fixed in master 24 days ago:
https://github.com/PoC-Consortium/burstcoin/commit/c320d23d26ec0ea2433792a692ad32aafdd622f6

closing.

**Closed by rico666** 2018-01-25 08:39 UTC
