### ISSUE TITLE
Wallet 2.0.0 showing as 1.3.6 and stuck in explorer

### ISSUE THREAD

**Issue by krispipeleers** [PoC-Consortium/burstcoin#190] opened 2018-03-20 15:31 UTC
Let me know what additional information you need:
https://explore.burst.cryptoguru.org/peer/138.91.182.37

Wallet is running and fully synced.

**Comment by ac0v** [comment] 2018-03-21 00:01
This is a duplicate of #177 the fix has already been merged to the branch 2.0 and will show up in 2.0.1

**Closed by ac0v** 2018-03-21 00:01 UTC
