### ISSUE TITLE
Block not accepted. Double spending transaction

### ISSUE THREAD

**Issue by Ready2Burst** [PoC-Consortium/burstcoin#208] opened 2018-03-29 00:51 UTC
Getting these over and over and cannot continue sync process. Popped off 100 blocks at 473490 and then received: 

> [INFO] 2018-03-28 20:48:50 brs.BlockchainProcessorImpl - Error: lastBlock is null

Followed by more "double spending" errors. Restarted wallet and still sitting at 473490 so the pop-off may not have worked. Still encountering error below:

> [SEVERE] 2018-03-28 20:44:57 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 600981998084891005 transaction: {"senderPublicKey":"05edad61dea46ca384108b3d9d4440394c566de31975ece00cc3e8d927dffd68","signature":"c04f274b9e768e2a71c7cfa081848a179a7b4ba418dfc296da56bd6d4e76630d45725f4f560fedc300ea808f29b46e40c673c73e124d12246765b9b60567223a","feeNQT":100000000,"type":20,"version":1,"ecBlockId":"14922037810432786612","attachment":{"version.RewardRecipientAssignment":1},"subtype":0,"amountNQT":0,"recipient":"15587859947385731145","ecBlockHeight":467371,"deadline":1440,"timestamp":114527695}
        at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:989)

**Comment by ocgit2015** [comment] 2018-03-29 08:36
I have the exact same problem,  but at block 473220.
Parameters... fresh install, of 2.0.1 with new database from scratch,.. upgraded half-way the sync process  to 2.0.2

All went fine until block 473220,  and now this wallet node is reported as stuck.




Mar 29, 2018 4:01:35 PM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version 2.0.2
Mar 29, 2018 4:01:36 PM org.ehcache.core.EhcacheManager createCache
INFO: Cache 'account' created in EhcacheManager.
[INFO] 2018-03-29 16:01:37 brs.db.sql.Db - Using mariadb Backend
[INFO] 2018-03-29 16:01:37 brs.db.mariadb.MariadbDbVersion - Database update may take a while if needed, current db version 177...
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.testUnconfirmedTransactions undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableProcessTransactionsThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableRemoveUnconfirmedTransactionsThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableRebroadcastTransactionsThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableGetMoreBlocksThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableImportBlocksThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableGenerateBlocksThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - P2P.myHallmark undefined. Default: >null<
[INFO] 2018-03-29 16:01:38 brs.Burst - P2P.BlacklistedPeers undefined. Default: >null<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.sendToPeersLimit undefined. Default: >0<
[INFO] 2018-03-29 16:01:38 brs.Burst - DEV.dumpPeersVersion undefined. Default: >null<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disablePeerConnectingThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disablePeerUnBlacklistingThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.disableGetMorePeersThread undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - JETTY.API.GzipFilter undefined. Default: >false<
[INFO] 2018-03-29 16:01:38 brs.Burst - brs.debugTraceAccounts undefined. Default: >null<
[INFO] 2018-03-29 16:01:39 brs.BlockchainProcessorImpl - Genesis block already in database
[INFO] 2018-03-29 16:01:39 brs.BlockchainProcessorImpl - Last block height: 473394
[INFO] 2018-03-29 16:01:39 brs.http.API - Started API server at 0.0.0.0:8125
[INFO] 2018-03-29 16:01:39 brs.peer.Peers - Started peer networking server at 0.0.0.0:8123
[INFO] 2018-03-29 16:01:39 brs.Burst - CPU.NumCores undefined. Default: >10<
[INFO] 2018-03-29 16:01:39 brs.Burst - Initialization took 3474 ms
[INFO] 2018-03-29 16:01:39 brs.Burst - BRS 2.0.2 started successfully.
[SEVERE] 2018-03-29 16:06:44 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 16313336267743366508 transaction: {"senderPublicKey":"30641740399ebd5a5705a50394cff7c666ee027963754528664f5e0b8f065e6b","signature":"e73d5e5309fa9f9aa1018cfca505566088a24083e35b3f4402440ab18defed073b1e07532ec0687188a1baf57854ffc2541df5b048460cff87fea07c98e52823","feeNQT":100000000,"type":0,"version":1,"ecBlockId":"5240349467762712416","attachment":{"version.Message":1,"messageIsText":true,"message":"60738ecf55694f12a30a332f16e88a6c8ec18a954b2d4e36ad06781209a2683a"},"subtype":0,"amountNQT":5000000000,"recipient":"13383190289605706987","ecBlockHeight":473220,"deadline":1440,"timestamp":114506652}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:989)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:961)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:266)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-03-29 16:06:44 brs.BlockchainProcessorImpl - Failed to parse block: {}java.lang.NullPointerException
java.lang.NullPointerException
	at brs.services.impl.BlockServiceImpl.calculateBaseTarget(BlockServiceImpl.java:240)
	at brs.BlockchainProcessorImpl$1.run(BlockchainProcessorImpl.java:450)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-03-29 16:06:44 brs.BlockchainProcessorImpl - Failed to parse block trace: [Ljava.lang.StackTraceElement;@40fc4a6e
[INFO] 2018-03-29 16:22:07 brs.peer.Peers - Finished connecting to 2 well known peers.
[INFO] 2018-03-29 16:22:07 brs.peer.Peers - You can open your Burst Wallet in your favorite browser with: http://127.0.0.1:8125 or http://localhost:8125

**Comment by Quibus-burst** [comment] 2018-03-29 09:32
You need to popoff some blocks aswell

Please upgrade to v2.0.2 and popoff about 100 blocks.
Popoff can be done by edit config file while wallet is offline and set API.Debug = on
After that when wallet is running you can go to http://localhost:8125/test
Under Debug in the bottom you find popoff

**Comment by ocgit2015** [comment] 2018-03-29 16:09
Thanks Quibus-burst.
That worked out well and wallet node is up to date now
<<>>

**Comment by Ready2Burst** [comment] 2018-03-30 16:40
Popping-off 400 blocks resolved this issue. However, popping-off 100 did not so when in doubt, pop-off a bit more, but less than 1400.

**Comment by llybin** [comment] 2018-03-31 07:55
2.0.2 synced from scratch again and stucked with error:
[SEVERE] 2018-03-31 07:53:40 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 15755028282436143015 transaction: {"senderPublicKey":"54debcb79532b0d0c0afef38213d13b04d06428347a26ef0660d31c296ab5e19","signature":"d06cf4dec6f1d5e82e865f57fcd547bfb38e3748e3ed9036cc8747133cdc72081470c88394aacb6526210902427a906dc3cb63fec1ff719016b8b05c6b7da826","feeNQT":100000000,"type":0,"version":1,"ecBlockId":"14922457765732618945","attachment":{"encryptedMessage":{"data":"9d1c4d1c775f5753afc21113fa5a0d791c91f78fe222ab2339b9b7c69fbf02780f71c5b66b18f0f3fcecf34dac0c67e559cc2b4f7fb9c31e671f44f11c53e861245b08ec66a6b6d401df4b68a853cb9c27a1989d0d37d7c1d7856b7ee53632fc","nonce":"e31c165efb4389b7dd0ea914a7e3e27b3dbdccc433328be447ee9cffbfd844f5","isText":true},"version.EncryptedMessage":1},"subtype":0,"amountNQT":4393729909,"recipient":"13383190289605706987","ecBlockHeight":474178,"deadline":1440,"timestamp":114700186}
        at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:989)
        at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:961)
        at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:266)
        at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by llybin** [comment] 2018-03-31 07:56
Reopen bug please. Bug is not solved!

**Comment by Quibus-burst** [comment] 2018-03-31 08:00
This bug is beeing worked on. and was beeing worked on despited this got closed.

**Comment by llybin** [comment] 2018-03-31 08:16
But my node stucked, and i see many nodes stucked on block: 474191 https://explore.burst.cryptoguru.org/tool/observe popoff everytime is not solution..

**Comment by Quibus-burst** [comment] 2018-03-31 08:20
As I said. It is beeing worked on. It is not a sustainable solution to popoff blocks all the time.

**Comment by matbogdan79** [comment] 2018-03-31 11:33
https://media.discordapp.net/attachments/349867938892873740/429594534964363265/unknown.png?width=566&height=615
and after popoff
https://cdn.discordapp.com/attachments/349867938892873740/429596279379591169/unknown.png

please try and fix this problems because with these problems BRS wallet can't be used in production env.

**Comment by Quibus-burst** [comment] 2018-03-31 14:32
It is related to forkhandling, Yes. The bug has been found and is addressed. Currently there is some tests going on to make sure it really is solved.

**Comment by ac0v** [comment] 2018-04-01 12:35
fixed in 2.0.3 - qbundle should be released during the next 24h.

**Closed by ac0v** 2018-04-01 12:35 UTC
Labels: bug

**Comment by ocgit2015** [comment] 2018-04-01 14:01
Installed 2.0.3 and popped off 500 blocks then  restarted version 2.0.3

Is there any other thing I need to do?

looks like I'm still stuck at block 474807, see below

./burst.sh
Apr 01, 2018 9:35:25 PM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version 2.0.3
Apr 01, 2018 9:35:25 PM org.ehcache.core.EhcacheManager createCache
INFO: Cache 'account' created in EhcacheManager.
[INFO] 2018-04-01 21:35:25 brs.db.sql.Db - Using mariadb Backend
[INFO] 2018-04-01 21:35:25 brs.db.mariadb.MariadbDbVersion - Database update may take a while if needed, current db version 177...
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.testUnconfirmedTransactions undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableProcessTransactionsThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableRemoveUnconfirmedTransactionsThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableRebroadcastTransactionsThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableGetMoreBlocksThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableImportBlocksThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableGenerateBlocksThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - P2P.myHallmark undefined. Default: >null<
[INFO] 2018-04-01 21:35:26 brs.Burst - P2P.BlacklistedPeers undefined. Default: >null<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.sendToPeersLimit undefined. Default: >0<
[INFO] 2018-04-01 21:35:26 brs.Burst - DEV.dumpPeersVersion undefined. Default: >null<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disablePeerConnectingThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disablePeerUnBlacklistingThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.disableGetMorePeersThread undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - JETTY.API.GzipFilter undefined. Default: >false<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.debugTraceQuote undefined. Default: >"<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.debugTraceSeparator undefined. Default: >	<
[INFO] 2018-04-01 21:35:26 brs.Burst - brs.debugTraceAccounts undefined. Default: >null<
[INFO] 2018-04-01 21:35:26 brs.BlockchainProcessorImpl - Genesis block already in database
[INFO] 2018-04-01 21:35:26 brs.BlockchainProcessorImpl - Last block height: 474807
[INFO] 2018-04-01 21:35:27 brs.http.API - Started API server at 0.0.0.0:8125
[INFO] 2018-04-01 21:35:27 brs.peer.Peers - Started peer networking server at 0.0.0.0:8123
[INFO] 2018-04-01 21:35:27 brs.Burst - Initialization took 1609 ms
[INFO] 2018-04-01 21:35:27 brs.Burst - BRS 2.0.3 started successfully.
[SEVERE] 2018-04-01 21:35:32 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 6194980708694807754 transaction: {"senderPublicKey":"f3f5a6dc1560d1213903cd8292a7b8eafe6feb252136e27cf746a91ea6cc3c18","attachment":{"quantityQNT":50,"priceNQT":2500000000,"asset":"12143106865567593139","version.BidOrderPlacement":1},"subtype":3,"amountNQT":0,"signature":"b88add862c62b19b106c518d059ac40926ab1d65c9f808c1461c3cb66f105a02c9c4561dea1977ef5c88e708c7588ef6113332882177803523b1e5ddbb6da95c","feeNQT":100000000,"ecBlockHeight":474801,"type":2,"deadline":1440,"version":1,"timestamp":114850674,"ecBlockId":"17084418411245094052"}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1000)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:974)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:273)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-04-01 21:35:41 brs.peer.Peers - Finished connecting to 4 well known peers.
[INFO] 2018-04-01 21:35:41 brs.peer.Peers - You can open your Burst Wallet in your favorite browser with: http://127.0.0.1:8125 or http://localhost:8125
[SEVERE] 2018-04-01 21:36:28 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 6194980708694807754 transaction: {"senderPublicKey":"f3f5a6dc1560d1213903cd8292a7b8eafe6feb252136e27cf746a91ea6cc3c18","attachment":{"quantityQNT":50,"priceNQT":2500000000,"asset":"12143106865567593139","version.BidOrderPlacement":1},"subtype":3,"amountNQT":0,"signature":"b88add862c62b19b106c518d059ac40926ab1d65c9f808c1461c3cb66f105a02c9c4561dea1977ef5c88e708c7588ef6113332882177803523b1e5ddbb6da95c","feeNQT":100000000,"ecBlockHeight":474801,"type":2,"deadline":1440,"version":1,"timestamp":114850674,"ecBlockId":"17084418411245094052"}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1000)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:974)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:273)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[SEVERE] 2018-04-01 21:36:40 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 6194980708694807754 transaction: {"senderPublicKey":"f3f5a6dc1560d1213903cd8292a7b8eafe6feb252136e27cf746a91ea6cc3c18","attachment":{"quantityQNT":50,"priceNQT":2500000000,"asset":"12143106865567593139","version.BidOrderPlacement":1},"subtype":3,"amountNQT":0,"signature":"b88add862c62b19b106c518d059ac40926ab1d65c9f808c1461c3cb66f105a02c9c4561dea1977ef5c88e708c7588ef6113332882177803523b1e5ddbb6da95c","feeNQT":100000000,"ecBlockHeight":474801,"type":2,"deadline":1440,"version":1,"timestamp":114850674,"ecBlockId":"17084418411245094052"}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1000)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:974)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:273)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[SEVERE] 2018-04-01 21:36:54 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 6194980708694807754 transaction: {"senderPublicKey":"f3f5a6dc1560d1213903cd8292a7b8eafe6feb252136e27cf746a91ea6cc3c18","attachment":{"quantityQNT":50,"priceNQT":2500000000,"asset":"12143106865567593139","version.BidOrderPlacement":1},"subtype":3,"amountNQT":0,"signature":"b88add862c62b19b106c518d059ac40926ab1d65c9f808c1461c3cb66f105a02c9c4561dea1977ef5c88e708c7588ef6113332882177803523b1e5ddbb6da95c","feeNQT":100000000,"ecBlockHeight":474801,"type":2,"deadline":1440,"version":1,"timestamp":114850674,"ecBlockId":"17084418411245094052"}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1000)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:974)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:273)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[SEVERE] 2018-04-01 21:37:04 brs.BlockchainProcessorImpl - Block not accepted
brs.BlockchainProcessor$TransactionNotAcceptedException: Double spending transaction: 6194980708694807754 transaction: {"senderPublicKey":"f3f5a6dc1560d1213903cd8292a7b8eafe6feb252136e27cf746a91ea6cc3c18","attachment":{"quantityQNT":50,"priceNQT":2500000000,"asset":"12143106865567593139","version.BidOrderPlacement":1},"subtype":3,"amountNQT":0,"signature":"b88add862c62b19b106c518d059ac40926ab1d65c9f808c1461c3cb66f105a02c9c4561dea1977ef5c88e708c7588ef6113332882177803523b1e5ddbb6da95c","feeNQT":100000000,"ecBlockHeight":474801,"type":2,"deadline":1440,"version":1,"timestamp":114850674,"ecBlockId":"17084418411245094052"}
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1000)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:974)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:273)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Quibus-burst** [comment] 2018-04-01 14:03
You might have hit a point where DB got corrupted. then you need to resync from scratch. Or bootstrap the chain from a healthy source.

**Comment by ocgit2015** [comment] 2018-04-01 14:06
Thanks for the fast reply.
I'll go for a re-sync from scratch with version 2.0.3

**Comment by ocgit2015** [comment] 2018-04-02 09:28
feedback:

Re-sync from scratch with version 2.0.3 works like a charm and completes without being stuck once.

end of feedback
