### ISSUE TITLE
2.0 blockchain sync fails on Mariadb. Cannot add or update a child row: a foreign key constraint fails

### ISSUE THREAD

**Issue by Ready2Burst** [PoC-Consortium/burstcoin#178] opened 2018-03-16 14:32 UTC
**Exception details:**

_Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
Query is: insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [-2605602709807211862,3,39445700,5048606780733928085,4643600000000,5100000000,1545,<bytearray:■√@Z?╢ä▀εÜƒL╙yàeè╠]Ä╚?xÿñ±¢:,>,<bytearray:ò2FPAF▓ß¼Yû▒Q?q|÷é)°,3>ûs└╬@>>,<bytearray:╟ºHΦú.>,3046283,163089,<^Σu²   ╠⌡V>,<bytearray:╙≡?▀ⁿDÿαHEπ»ΦZb?_÷l
h┐=Ço╞° αç)¡@Vgà[·ùe?╠p╦ú╕ér72;H┼≈ä⌐^>,<bytearray:<ª#╥W▐]₧ªå/σ^δ5┘OVt£╜S╦┤ƒ>U╚?è>,-797952578347163983,670066090681771847,<null>]
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)_
        
**Steps to Reproduce:**

1. Started with an in-sync 1.3.6 wallet and QBundle. Shut both of those down.
1. Ran 2.0 wallet, let it sync for 60 secs, stopped it. Thought a database-copy would be faster.
2. Ran 1.3.6 (QB) and "switched db's from H2 to maria" in hopes I could avoid downloading the entire BC. The H2 -> Maria piece took a bit but 'appeared' to work (no errors in the UI and received a "success" message). Stopped 1.3.6 wallet (actually it must be stopped in order to copy-db anyway).
3. Ran 2.0 but the H2-sourced data wasn't there. Ran some queries in Heidi and the H2 data never made it over, no idea how "copy database" even worked in QB, it probably generated migration scripts but never executed them (my guess).
4. Let 2.0 sync again over night, woke up to these errors. Confirmed that the block_id's that are referenced in the SQL statement do not in fact exist, hence the FK constraint exception.
5. According to the wallet UI, roughly 30% of the BC was downloaded and synced. 

**Take-away:**

Could the H2-to-Maria copy have left Maria in a broken state? Possible, but none of the data seemed to actually make it to Maria. There were very few account rows (~6000) and those were probably from step 2 above.

**Comment by alexdohmen** [comment] 2018-03-17 07:57
Getting the same error for a fresh install.

**Comment by rico666** [comment] 2018-03-17 08:07
Need more info:

Which OS? Which block height? Does a restart (and if not: a block popoff) rectify the situation or not?

**Comment by kmh3785** [comment] 2018-03-17 14:12
I'm getting the same error on a fresh install, using MariaDB and downloading the blockchain fresh.

I'm on Win 10 Home, 64-bit - version 17099 - build 16299.248

**Comment by bradfordcp** [comment] 2018-03-17 14:57
I've seen this error on a fresh install, CentOS 7, MariaDB 5.5.56. Can the block height can be pulled from the stacktrace?

```
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=1032) Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:171)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:452)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 14 more
Caused by: java.sql.SQLException: Cannot add or update a child row: a foreign key constraint fails (`burstwallet`.`block`, CONSTRAINT `constraint_3c` FOREIGN KEY (`previous_block_id`) REFERENCES `block` (`id`) ON DELETE CASCADE)
Query is: insert into `block` (`id`, `version`, `timestamp`, `previous_block_id`, `total_amount`, `total_fee`, `payload_length`, `generator_public_key`, `previous_block_hash`, `cumulative_difficulty`, `base_target`, `height`, `generation_signature`, `block_signature`, `payload_hash`, `generator_id`, `nonce`, `ats`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [-2605602709807211862,3,39445700,5048606780733928085,4643600000000,5100000000,1545,<bytearray:��@Z����L�y�e��]��?x���:,>,<bytearray:�2FPAF��Y��Q�q|��)�,^�u�Z��>��V>,<bytearray:��?��D��HE��Zb�_�l<bytearray:����R��kk�?l
h�=�o��	��)�@Vg�[��e��pˣ��r72;H����^>,<bytearray:<�#�W�]���/�^�5�Ot��S˴�>U�?�>,-797952578347163983,670066090681771847,<null>]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 21 more
```

The last height in the UI is `163088`

**Comment by bradfordcp** [comment] 2018-03-17 15:26
Popping 10 blocks off an restarting the DB sync back up to height `163088` before throwing the error message again.

**Comment by Ready2Burst** [comment] 2018-03-17 15:32
Reproduced the problem again, Windows 10.

1. Deleted burstwallet db
2. Recreated empty burstwallet db
3. Ran 2.0 wallet and let it run overnight, same exceptions occurred.

Highest block max(db_id) looks like this:

![image](https://user-images.githubusercontent.com/6651501/37557160-d6d100cc-29d6-11e8-8b3a-ee9aaad026ca.png)

**Comment by alexdohmen** [comment] 2018-03-17 15:47
I am on latest docker / alpine linux, MariaDB 10.2.13
Restarted the sync now

**Comment by ac0v** [comment] 2018-03-17 19:10
it could be an encoding issue (eg. lating1)
could you provide a `show create database ...` ?

**Comment by alexdohmen** [comment] 2018-03-17 21:56
... `burstwallet` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */

**Comment by Ready2Burst** [comment] 2018-03-17 22:44
I used the default collation in Heidi, I believe it was Latin1. What should it be?

**Comment by alexdohmen** [comment] 2018-03-18 11:46
I switched from alpine to ubuntu because of some network trouble. After some hours of waiting this error was thrown (followed by the constraint error seen above):

[SEVERE] 2018-03-18 11:41:54 brs.BlockchainProcessorImpl - Uncaught exception in blockImporterThread
org.jooq.exception.DataAccessException: SQL [insert into `purchase_public_feedback` (`id`, `public_feedback`, `height`, `latest`) values (?, ?, ?, ?) on duplicate key update `purchase_public_feedback`.`id` = ?, `purchase_public_feedback`.`public_feedback` = ?, `purchase_public_feedback`.`height` = ?, `purchase_public_feedback`.`latest` = ?]; (conn=3229) Incorrect string value: '\xD0\xA0\xD0\xB0\xD0\xB1...' for column 'public_feedback' at row 1
	at org.jooq_3.10.5.MARIADB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2239)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:361)
	at brs.db.sql.DbUtils.mergeInto(DbUtils.java:46)
	at brs.db.sql.SqlDigitalGoodsStoreStore$7.save(SqlDigitalGoodsStoreStore.java:135)
	at brs.db.sql.SqlDigitalGoodsStoreStore$7.save(SqlDigitalGoodsStoreStore.java:119)
	at brs.db.sql.ValuesSqlTable.insert(ValuesSqlTable.java:90)
	at brs.services.impl.DGSGoodsStoreServiceImpl.addPublicFeedback(DGSGoodsStoreServiceImpl.java:201)
	at brs.services.impl.DGSGoodsStoreServiceImpl.feedback(DGSGoodsStoreServiceImpl.java:188)
	at brs.TransactionType$DigitalGoods$7.applyAttachment(TransactionType.java:1397)
	at brs.TransactionType.apply(TransactionType.java:262)
	at brs.Attachment$AbstractAttachment.apply(Attachment.java:107)
	at brs.services.impl.TransactionServiceImpl.apply(TransactionServiceImpl.java:67)
	at brs.services.impl.BlockServiceImpl.apply(BlockServiceImpl.java:162)
	at brs.BlockchainProcessorImpl.accept(BlockchainProcessorImpl.java:1009)
	at brs.BlockchainProcessorImpl.pushBlock(BlockchainProcessorImpl.java:950)
	at brs.BlockchainProcessorImpl.lambda$new$7(BlockchainProcessorImpl.java:270)
	at brs.util.ThreadPool.lambda$start$0(ThreadPool.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLDataException: (conn=3229) Incorrect string value: '\xD0\xA0\xD0\xB0\xD0\xB1...' for column 'public_feedback' at row 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:167)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:228)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
	... 22 more
Caused by: java.sql.SQLException: Incorrect string value: '\xD0\xA0\xD0\xB0\xD0\xB1...' for column 'public_feedback' at row 1
Query is: insert into `purchase_public_feedback` (`id`, `public_feedback`, `height`, `latest`) values (?, ?, ?, ?) on duplicate key update `purchase_public_feedback`.`id` = ?, `purchase_public_feedback`.`public_feedback` = ?, `purchase_public_feedback`.`height` = ?, `purchase_public_feedback`.`latest` = ?, parameters [1710269572086834694,'Работает!',163088,1,1710269572086834694,'Работает!',163088,1]
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 28 more

**Comment by bradfordcp** [comment] 2018-03-18 15:52
The [solution](https://github.com/PoC-Consortium/burstcoin/issues/184#issuecomment-373944886) in #184 solved the problem for me. I'm up to block 350k+ and it's still running.

**Comment by alpha13fr** [comment] 2018-03-18 22:45
idem, all is ok w10 and my wallet is synchronize

**Comment by alexdohmen** [comment] 2018-03-19 07:27
yes, its working, from my side this issue is resolved

**Comment by rico666** [comment] 2018-03-19 08:05
Very well. Thanks for your reports and patience gentlemen. Closing.

**Closed by rico666** 2018-03-19 08:05 UTC

**Comment by Ready2Burst** [comment] 2018-03-19 13:19
Confirmed using this collation fixes the problem:

create database burstwallet DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
